version: '3.9'
services:
  mariadb:
    image: mariadb:10.5.9
    env_file:
     - .env
    ports:
      - 3306:3306
    volumes:
     - database:/var/lib/mysql

  adminer:
    image: adminer:4.8.0
    ports:
      - 9999:8080

volumes:
  database: